### ISSUE TITLE
Can react-swipe-views be a pure component?

### ISSUE THREAD

**Issue by hugooliveirad** [damusnet/react-swipe-views#1]
It would be awesome to use react-swipe-views as a pure component. This means it would not use state to change views, but props.

We would need a way to set the current view and to add a handler to the onChange event.

This makes it easier to test, easier to manage with a router and easier to use in flux apps.

**Comment by damusnet** [comment]
That's definitely worth looking into. It seems entirely possible, however that would mean there would have to be a lot more code in the parent component to handle the props and pass them back to react-swipe-views. Once you go down this road, and since react-swipe-views is less than 200 lines, it seems almost easier to fork the code for your own use-case. Unless I am missing something there.

I am going to implement this component in an ongoing project in the next few days so I will see how I need to make it evolve since I also plan to use a router in a flux app. Thanks for your feedback in any case, and feel free to make a PR!

**Comment by hugooliveirad** [comment]
To use it in a router (with the router controlling which tab is active), I think you will need this :P.

I can imagine just some line of codes in the parent. I'll send a PR with an example soon :)

**Comment by damusnet** [comment]
I have figured out a way to make react-swipe-views interact with react-router and vice versa. Please check out fb6fae46c7f42c9302b229012b6b3329e5dbddba and tell me what you think. I have updated the [npm-webpack example](https://github.com/damusnet/react-swipe-views/tree/master/examples/npm-webpack) to reflect the changes.

To change the selected tab you still can't pass a props or anything, but you should be able to call the [transitionTo()](https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md#transitiontoroutenameorpath-params-query) method from react-router anywhere in your app!

**Comment by ferrannp** [comment]
Hi @damusnet ! Thanks for the work. I was trying the example mmmm I noticed, it only changes the url correctly if you click exactly the title of the tab (but not if you click outside the title but still in the tab). The button in Thanks for "Back to intro" doesn't really bring you to the intro (just changes the url). Going also directly to: http://localhost:3000/code does not work (goes to the intro). I am going to try playing with transitionTo() and see what I get.

Although, I am not sure if I will make it to work without access to `selectedIndex` (how to make the correct tab to be selected?)

**Comment by damusnet** [comment]
Hi, thanks for your feedback. Please forgive me, I'm pretty sure the reason it didn't work for you is because I totally forgot to bump all the version numbers and to publish again on npm and bower! I just did all that, removed my local version and git cloned it again, npm install, npm start, and it works as expected. Please do the same and tell me if it works better. It worked locally for me because I use `npm link` to develop instead of relying on the public version.

The problem with having to click exactly the title of the tab was real however (noticed it before and forgot to fix it) and should be better now. Just had to make the <a> tag wider.

When everything works, the way to make the correct tab selected is by using urls and react-router. The react-swipe-views component will automatically read the url and select the correct tab accordingly.

**Comment by ferrannp** [comment]
Yeeeey. Works much, much better :D. The only 'thing' I found it's that I still click sometimes and it changes tab/content but not the url neither the title in bold. I see not all the tab contains the link... Is not possible to make all the tab (li) clickable and when handle the click make a transition to the route (with transitionTo) ?

![Imgur](http://i.imgur.com/dAn0wdR.png)

Maybe having a callback that fires when selectedIndex changes? But that would be repeated work I think... First option is better(`li`clickable and `transitionTo`). Basically, the same that is in `_handleTouchEnd`, wouldn't work also in `_handleClick`?

```
  if (this.context.router) {
    var child = this.props.children[selectedIndex];
    var to = child.props.title.props.to;
    this.context.router.transitionTo(to);
  }
```

Another small thing is that if there is no route in the url (just localhost:3000, there is no title selected).

**Comment by damusnet** [comment]
The behavior you found seems to only happen in a desktop browser, whereas react-swipe-views was primarily intended for mobile use. However a quick fix was easy to implement by calling transitionTo regardless when a <li> tag is clicked. The code was already there for the touchEnd event, and it was just a matter of refactoring it for reuse. v0.0.4 should work in every situation! Thanks a lot for your valuable debugging!

React-router presence is always tested before calling transitionTo so that it remains useable even without it :)

**Comment by ferrannp** [comment]
I've just seen it! I am already implementing it for my we :) Thanks a lot eh. Mmm I'm sorry for being so ball breaker but I saw also you fixed that going to `localhost:3000`selects the first tab correctly now... However, if then you click another tab, and go back to localhost:3000, it does not work correctly. I should apply for beta tester haha.

**Comment by damusnet** [comment]
You should definitely be a beta tester!

I see what you mean, but I don't think that's really a bug. It's just that I configured the example app routes with "/" as the default calling {App} and "/intro" as the real route for the first tab of {App}. I did this because I wanted all three tabs to have a different url. In a real case you would probably not give two urls to the same view. I'll probably correct the example to avoid this issue.

However this made me realize that the "back" button is now kind of broken. Because transitionTo is sometimes called twice (once by the onClick() event, and once by the componentWillReceiveProps() event) you have to go back twice to go to the previous tab. I'll fix this tomorrow by checking wether we already are on the correct tab or not before calling transitionTo.

**Comment by damusnet** [comment]
Hey @hugobessaa, I implemented a solution to using this component as a pure one.
Check out the [Bower/Brunch example](https://github.com/damusnet/react-swipe-views/releases/tag/v0.0.7) and tell me what you think :)

**Comment by hugooliveirad** [comment]
Awesome @damusnet! Functional UIs thank you haha.

Sorry for not being able to create an example for you, I was really busy last week.

Glad this is working now :smile:

**Comment by damusnet** [comment]
:+1:
